
namespace PokemonGen3Hack.Pokemon {
  public enum GenderGroup {
    Male = 0x0,
    M7F1 = 0x1F,
    M3F1 = 0x3F,
    M1F1 = 0x7F,
    M1F3 = 0xBF,
    M1F7 = 0xE1,
    Female = 0xFE,
    Unknown = 0xFF,
  }
  public enum Gender { Male = 0x0, Female = 0xFE, Unknown = 0xFF }
  public enum TrainerGender { Male, Female }
  public enum PokemonLanguage {
    Japanese = 1,
    English,
    French,
    Italian,
    German,
    unused,
    Spanish,
  }
  public enum Nature {
    Hardy,
    Lonely,
    Brave,
    Adamant,
    Naughty,
    Bold,
    Docile,
    Relaxed,
    Impish,
    Lax,
    Timid,
    Hasty,
    Serious,
    Jolly,
    Naive,
    Modest,
    Mild,
    Quiet,
    Bashful,
    Rash,
    Calm,
    Gentle,
    Sassy,
    Careful,
    Quirky,
  }
  public enum SubstructureOrder {
    GAEM, GAME, GEAM, GEMA,
    GMAE, GMEA, AGEM, AGME,
    AEGM, AEMG, AMGE, AMEG,
    EGAM, EGMA, EAGM, EAMG,
    EMGA, EMAG, MGAE, MGEA,
    MAGE, MAEG, MEGA, MEAG,
  }
  public enum StatusCondition {
    None = 0,
    Sleep = 2, // 0~2를 사용하며 001~111 (1~7턴)
    Poison = 0x8,
    Burn = 0x10,
    Freeze = 0x20,
    Paralysis = 0x40,
    BadPoison = 0x80
  }
  public enum PokemonType {
    Normal,
    Fighting,
    Flying,
    Poison,
    Ground,
    Rock,
    Bug,
    Ghost,
    Steel,
    Unknown,
    Fire,
    Water,
    Grass,
    Electric,
    Psychic,
    Ice,
    Dragon,
    Dark,
  }
  public enum HiddenPowerType {
    Fighting,
    Flying,
    Poison,
    Ground,
    Rock,
    Bug,
    Ghost,
    Steel,
    Fire,
    Water,
    Grass,
    Electric,
    Psychic,
    Ice,
    Dragon,
    Dark,
  }
  public enum GameVersion {
    Sapphire = 1,
    Ruby,
    Emerald,
    FireRed,
    LeafGreen,
    ColosseumOrXD = 0xF,
  }
  public enum Pokeball {
    MasterBall = 1,
    UltraBall,
    GreatBall,
    PokeBall,
    SafariBall,
    NetBall,
    DiveBall,
    NestBall,
    RepeatBall,
    TimerBall,
    LuxuryBall,
    PremierBall,
  }
  public enum Ribbon {
    Cool,
    Beauty,
    Cute,
    Smart,
    Tough,
    Champion,
    Winning,
    Victory,
    Artist,
    Effort,
    BattleChampion,
    RegionalChampion,
    NationalChampion,
    Country,
    National,
    Earth,
    World,
    None,
  }

  public interface IConst {
    public Dictionary<Gender, string> Gender { get; }
    public Dictionary<Nature, string> Nature { get; }
    public Dictionary<StatusCondition, string> StatusCondition { get; }
    public Dictionary<Pokeball, string> Pokeball { get; }
    public Dictionary<PokemonLanguage, string> Language { get; }
    public string[] StatNames { get; }
    public string[] Locations { get; }
    public Dictionary<int, string> Moves { get; }
    public Dictionary<Ribbon, string> Ribbons { get; }
    public Dictionary<PokemonType, string> PokemonTypes { get; }
    public Dictionary<HiddenPowerType, string> HiddenPowerTypes { get; }
  }

  public class ConstEN : IConst {
    public Dictionary<Gender, string> Gender {
      get => new() {
        { Pokemon.Gender.Male, "Male" },
        { Pokemon.Gender.Female, "Female" },
        { Pokemon.Gender.Unknown, "Unknown" }
      };
    }
    public Dictionary<Nature, string> Nature {
      get => new() {
        { Pokemon.Nature.Hardy, "Hardy" },
        { Pokemon.Nature.Lonely, "Lonely" },
        { Pokemon.Nature.Brave, "Brave" },
        { Pokemon.Nature.Adamant, "Adamant" },
        { Pokemon.Nature.Naughty, "Naughty" },
        { Pokemon.Nature.Bold, "Bold" },
        { Pokemon.Nature.Docile, "Docile" },
        { Pokemon.Nature.Relaxed, "Relaxed" },
        { Pokemon.Nature.Impish, "Impish" },
        { Pokemon.Nature.Lax, "Lax" },
        { Pokemon.Nature.Timid, "Timid" },
        { Pokemon.Nature.Hasty, "Hasty" },
        { Pokemon.Nature.Serious, "Serious" },
        { Pokemon.Nature.Jolly, "Jolly" },
        { Pokemon.Nature.Naive, "Naive" },
        { Pokemon.Nature.Modest, "Modest" },
        { Pokemon.Nature.Mild, "Mild" },
        { Pokemon.Nature.Quiet, "Quiet" },
        { Pokemon.Nature.Bashful, "Bashful" },
        { Pokemon.Nature.Rash, "Rash" },
        { Pokemon.Nature.Calm, "Calm" },
        { Pokemon.Nature.Gentle, "Gentle" },
        { Pokemon.Nature.Sassy, "Sassy" },
        { Pokemon.Nature.Careful, "Careful" },
        { Pokemon.Nature.Quirky, "Quirky" },
      };
    }
    public Dictionary<StatusCondition, string> StatusCondition {
      get => new() {
        { Pokemon.StatusCondition.None, "None" },
        { Pokemon.StatusCondition.Sleep, "Sleep" },
        { Pokemon.StatusCondition.Poison, "Poison" },
        { Pokemon.StatusCondition.Burn, "Burn" },
        { Pokemon.StatusCondition.Freeze, "Freeze" },
        { Pokemon.StatusCondition.Paralysis, "Paralysis" },
        { Pokemon.StatusCondition.BadPoison, "BadPoison" },
      };
    }
    public Dictionary<Pokeball, string> Pokeball {
      get => new() {
        { Pokemon.Pokeball.MasterBall, "MasterBall" },
        { Pokemon.Pokeball.UltraBall, "UltraBall" },
        { Pokemon.Pokeball.GreatBall, "GreatBall" },
        { Pokemon.Pokeball.PokeBall, "PokeBall" },
        { Pokemon.Pokeball.SafariBall, "SafariBall" },
        { Pokemon.Pokeball.NetBall, "NetBall" },
        { Pokemon.Pokeball.DiveBall, "DiveBall" },
        { Pokemon.Pokeball.NestBall, "NestBall" },
        { Pokemon.Pokeball.RepeatBall, "RepeatBall" },
        { Pokemon.Pokeball.TimerBall, "TimerBall" },
        { Pokemon.Pokeball.LuxuryBall, "LuxuryBall" },
        { Pokemon.Pokeball.PremierBall, "PremierBall" },
      };
    }
    public Dictionary<PokemonLanguage, string> Language {
      get => new() {
        { PokemonLanguage.Japanese, "Japanese" },
        { PokemonLanguage.English, "English" },
        { PokemonLanguage.French, "French" },
        { PokemonLanguage.Italian, "Italian" },
        { PokemonLanguage.German, "German" },
        { PokemonLanguage.unused, "unused" },
        { PokemonLanguage.Spanish, "Spanish" },
      };
    }
    public string[] StatNames { get => ["HP", "Attack", "Defense", "Speed", "SpecialAttack", "SpecialDefense"]; }
    public string[] Locations {
      get => [
        "Littleroot Town",
        "Oldale Town",
        "Dewford Town",
        "Lavaridge Town",
        "Fallarbor Town",
        "Verdanturf Town",
        "Pacifidlog Town",
        "Petalburg City",
        "Slateport City",
        "Mauville City",
        "Rustboro City",
        "Fortree City",
        "Lilycove City",
        "Mossdeep City",
        "Sootopolis City",
        "Ever Grande City",
        "Route 101",
        "Route 102",
        "Route 103",
        "Route 104",
        "Route 105",
        "Route 106",
        "Route 107",
        "Route 108",
        "Route 109",
        "Route 110",
        "Route 111",
        "Route 112",
        "Route 113",
        "Route 114",
        "Route 115",
        "Route 116",
        "Route 117",
        "Route 118",
        "Route 119",
        "Route 120",
        "Route 121",
        "Route 122",
        "Route 123",
        "Route 124",
        "Route 125",
        "Route 126",
        "Route 127",
        "Route 128",
        "Route 129",
        "Route 130",
        "Route 131",
        "Route 132",
        "Route 133",
        "Route 134",
        "Underwater (Route 124)",
        "Underwater (Route 126)",
        "Underwater (Route 127)",
        "Underwater (Route 128)",
        "Underwater (Sootopolis City)",
        "Granite Cave",
        "Mt. Chimney",
        "Safari Zone",
        "Battle Frontier",
        "Petalburg Woods",
        "Rusturf Tunnel",
        "Abandoned Ship",
        "New Mauville",
        "Meteor Falls",
        "Meteor Falls (unused)",
        "Mt. Pyre",
        "Aqua Hideout",
        "Shoal Cave",
        "Seafloor Cavern",
        "Underwater (Seafloor Cavern)",
        "Victory Road",
        "Mirage Island",
        "Cave of Origin",
        "Southern Island",
        "Fiery Path",
        "Fiery Path (unused)",
        "Jagged Pass",
        "Jagged Pass (unused)",
        "Sealed Chamber",
        "Underwater (Route 134)",
        "Scorched Slab",
        "Island Cave",
        "Desert Ruins",
        "Ancient Tomb",
        "Inside of Truck",
        "Sky Pillar",
        "Secret Base",
        "S.S. Tidal",
        "Pallet Town",
        "Viridian City",
        "Pewter City",
        "Cerulean City",
        "Lavender Town",
        "Vermilion City",
        "Celadon City",
        "Fuchsia City",
        "Cinnabar Island",
        "Indigo Plateau",
        "Saffron City",
        "Route 4 (Pokémon Center)",
        "Route 10 (Pokémon Center)",
        "Route 1",
        "Route 2",
        "Route 3",
        "Route 4",
        "Route 5",
        "Route 6",
        "Route 7",
        "Route 8",
        "Route 9",
        "Route 10",
        "Route 11",
        "Route 12",
        "Route 13",
        "Route 14",
        "Route 15",
        "Route 16",
        "Route 17",
        "Route 18",
        "Route 19",
        "Route 20",
        "Route 21",
        "Route 22",
        "Route 23",
        "Route 24",
        "Route 25",
        "Viridian Forest",
        "Mt. Moon",
        "S.S. Anne",
        "Underground Path (Routes 5-6)",
        "Underground Path (Routes 7-8)",
        "Diglett's Cave",
        "Victory Road",
        "Rocket Hideout",
        "Silph Co.",
        "Pokémon Mansion",
        "Safari Zone",
        "Pokémon League",
        "Rock Tunnel",
        "Seafoam Islands",
        "Pokémon Tower",
        "Cerulean Cave",
        "Power Plant",
        "One Island",
        "Two Island",
        "Three Island",
        "Four Island",
        "Five Island",
        "Seven Island",
        "Six Island",
        "Kindle Road",
        "Treasure Beach",
        "Cape Brink",
        "Bond Bridge",
        "Three Isle Port",
        "Sevii Isle 6",
        "Sevii Isle 7",
        "Sevii Isle 8",
        "Sevii Isle 9",
        "Resort Gorgeous",
        "Water Labyrinth",
        "Five Isle Meadow",
        "Memorial Pillar",
        "Outcast Island",
        "Green Path",
        "Water Path",
        "Ruin Valley",
        "Trainer Tower (exterior)",
        "Canyon Entrance",
        "Sevault Canyon",
        "Tanoby Ruins",
        "Sevii Isle 22",
        "Sevii Isle 23",
        "Sevii Isle 24",
        "Navel Rock",
        "Mt. Ember",
        "Berry Forest",
        "Icefall Cave",
        "Rocket Warehouse",
        "Trainer Tower",
        "Dotted Hole",
        "Lost Cave",
        "Pattern Bush",
        "Altering Cave",
        "Tanoby Chambers",
        "Three Isle Path",
        "Tanoby Key",
        "Birth Island",
        "Monean Chamber",
        "Liptoo Chamber",
        "Weepth Chamber",
        "Dilford Chamber",
        "Scufib Chamber",
        "Rixy Chamber",
        "Viapois Chamber",
        "Ember Spa",
        "Special Area",
        "Aqua Hideout",
        "Magma Hideout",
        "Mirage Tower",
        "Birth Island",
        "Faraway Island",
        "Artisan Cave",
        "Marine Cave",
        "Underwater (Marine Cave)",
        "Terra Cave",
        "Underwater (Route 105)",
        "Underwater (Route 125)",
        "Underwater (Route 129)",
        "Desert Underpass",
        "Altering Cave",
        "Navel Rock",
        "Trainer Hill",
        "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "",
        "(gift egg)",
        "(in-game trade)",
        "(fateful encounter)",
      ];
    }
    public Dictionary<int, string> Moves {
      get => new() {
        { 001, "POUND" },
        { 002, "KARATE CHOP" },
        { 003, "DOUBLESLAP" },
        { 004, "COMET PUNCH" },
        { 005, "MEGA PUNCH" },
        { 006, "PAY DAY" },
        { 007, "FIRE PUNCH" },
        { 008, "ICE PUNCH" },
        { 009, "THUNDERPUNCH" },
        { 010, "SCRATCH" },
        { 011, "VICEGRIP" },
        { 012, "GUILLOTINE" },
        { 013, "RAZOR WIND" },
        { 014, "SWORDS DANCE" },
        { 015, "CUT" },
        { 016, "GUST" },
        { 017, "WING ATTACK" },
        { 018, "WHIRLWIND" },
        { 019, "FLY" },
        { 020, "BIND" },
        { 021, "SLAM" },
        { 022, "VINE WHIP" },
        { 023, "STOMP" },
        { 024, "DOUBLE KICK" },
        { 025, "MEGA KICK" },
        { 026, "JUMP KICK" },
        { 027, "ROLLING KICK" },
        { 028, "SAND-ATTACK" },
        { 029, "HEADBUTT" },
        { 030, "HORN ATTACK" },
        { 031, "FURY ATTACK" },
        { 032, "HORN DRILL" },
        { 033, "TACKLE" },
        { 034, "BODY SLAM" },
        { 035, "WRAP" },
        { 036, "TAKE DOWN" },
        { 037, "THRASH" },
        { 038, "DOUBLE-EDGE" },
        { 039, "TAIL WHIP" },
        { 040, "POISON STING" },
        { 041, "TWINEEDLE" },
        { 042, "PIN MISSILE" },
        { 043, "LEER" },
        { 044, "BITE" },
        { 045, "GROWL" },
        { 046, "ROAR" },
        { 047, "SING" },
        { 048, "SUPERSONIC" },
        { 049, "SONICBOOM" },
        { 050, "DISABLE" },
        { 051, "ACID" },
        { 052, "EMBER" },
        { 053, "FLAMETHROWER" },
        { 054, "MIST" },
        { 055, "WATER GUN" },
        { 056, "HYDRO PUMP" },
        { 057, "SURF" },
        { 058, "ICE BEAM" },
        { 059, "BLIZZARD" },
        { 060, "PSYBEAM" },
        { 061, "BUBBLEBEAM" },
        { 062, "AURORA BEAM" },
        { 063, "HYPER BEAM" },
        { 064, "PECK" },
        { 065, "DRILL PECK" },
        { 066, "SUBMISSION" },
        { 067, "LOW KICK" },
        { 068, "COUNTER" },
        { 069, "SEISMIC TOSS" },
        { 070, "STRENGTH" },
        { 071, "ABSORB" },
        { 072, "MEGA DRAIN" },
        { 073, "LEECH SEED" },
        { 074, "GROWTH" },
        { 075, "RAZOR LEAF" },
        { 076, "SOLARBEAM" },
        { 077, "POISONPOWDER" },
        { 078, "STUN SPORE" },
        { 079, "SLEEP POWDER" },
        { 080, "PETAL DANCE" },
        { 081, "STRING SHOT" },
        { 082, "DRAGON RAGE" },
        { 083, "FIRE SPIN" },
        { 084, "THUNDERSHOCK" },
        { 085, "THUNDERBOLT" },
        { 086, "THUNDER WAVE" },
        { 087, "THUNDER" },
        { 088, "ROCK THROW" },
        { 089, "EARTHQUAKE" },
        { 090, "FISSURE" },
        { 091, "DIG" },
        { 092, "TOXIC" },
        { 093, "CONFUSION" },
        { 094, "PSYCHIC" },
        { 095, "HYPNOSIS" },
        { 096, "MEDITATE" },
        { 097, "AGILITY" },
        { 098, "QUICK ATTACK" },
        { 099, "RAGE" },
        { 100, "TELEPORT" },
        { 101, "NIGHT SHADE" },
        { 102, "MIMIC" },
        { 103, "SCREECH" },
        { 104, "DOUBLE TEAM" },
        { 105, "RECOVER" },
        { 106, "HARDEN" },
        { 107, "MINIMIZE" },
        { 108, "SMOKESCREEN" },
        { 109, "CONFUSE RAY" },
        { 110, "WITHDRAW" },
        { 111, "DEFENSE CURL" },
        { 112, "BARRIER" },
        { 113, "LIGHT SCREEN" },
        { 114, "HAZE" },
        { 115, "REFLECT" },
        { 116, "FOCUS ENERGY" },
        { 117, "BIDE" },
        { 118, "METRONOME" },
        { 119, "MIRROR MOVE" },
        { 120, "SELFDESTRUCT" },
        { 121, "EGG BOMB" },
        { 122, "LICK" },
        { 123, "SMOG" },
        { 124, "SLUDGE" },
        { 125, "BONE CLUB" },
        { 126, "FIRE BLAST" },
        { 127, "WATERFALL" },
        { 128, "CLAMP" },
        { 129, "SWIFT" },
        { 130, "SKULL BASH" },
        { 131, "SPIKE CANNON" },
        { 132, "CONSTRICT" },
        { 133, "AMNESIA" },
        { 134, "KINESIS" },
        { 135, "SOFTBOILED" },
        { 136, "HI JUMP KICK" },
        { 137, "GLARE" },
        { 138, "DREAM EATER" },
        { 139, "POISON GAS" },
        { 140, "BARRAGE" },
        { 141, "LEECH LIFE" },
        { 142, "LOVELY KISS" },
        { 143, "SKY ATTACK" },
        { 144, "TRANSFORM" },
        { 145, "BUBBLE" },
        { 146, "DIZZY PUNCH" },
        { 147, "SPORE" },
        { 148, "FLASH" },
        { 149, "PSYWAVE" },
        { 150, "SPLASH" },
        { 151, "ACID ARMOR" },
        { 152, "CRABHAMMER" },
        { 153, "EXPLOSION" },
        { 154, "FURY SWIPES" },
        { 155, "BONEMERANG" },
        { 156, "REST" },
        { 157, "ROCK SLIDE" },
        { 158, "HYPER FANG" },
        { 159, "SHARPEN" },
        { 160, "CONVERSION" },
        { 161, "TRI ATTACK" },
        { 162, "SUPER FANG" },
        { 163, "SLASH" },
        { 164, "SUBSTITUTE" },
        { 165, "STRUGGLE" },
        { 166, "SKETCH" },
        { 167, "TRIPLE KICK" },
        { 168, "THIEF" },
        { 169, "SPIDER WEB" },
        { 170, "MIND READER" },
        { 171, "NIGHTMARE" },
        { 172, "FLAME WHEEL" },
        { 173, "SNORE" },
        { 174, "CURSE" },
        { 175, "FLAIL" },
        { 176, "CONVERSION 2" },
        { 177, "AEROBLAST" },
        { 178, "COTTON SPORE" },
        { 179, "REVERSAL" },
        { 180, "SPITE" },
        { 181, "POWDER SNOW" },
        { 182, "PROTECT" },
        { 183, "MACH PUNCH" },
        { 184, "SCARY FACE" },
        { 185, "FAINT ATTACK" },
        { 186, "SWEET KISS" },
        { 187, "BELLY DRUM" },
        { 188, "SLUDGE BOMB" },
        { 189, "MUD-SLAP" },
        { 190, "OCTAZOOKA" },
        { 191, "SPIKES" },
        { 192, "ZAP CANNON" },
        { 193, "FORESIGHT" },
        { 194, "DESTINY BOND" },
        { 195, "PERISH SONG" },
        { 196, "ICY WIND" },
        { 197, "DETECT" },
        { 198, "BONE RUSH" },
        { 199, "LOCK-ON" },
        { 200, "OUTRAGE" },
        { 201, "SANDSTORM" },
        { 202, "GIGA DRAIN" },
        { 203, "ENDURE" },
        { 204, "CHARM" },
        { 205, "ROLLOUT" },
        { 206, "FALSE SWIPE" },
        { 207, "SWAGGER" },
        { 208, "MILK DRINK" },
        { 209, "SPARK" },
        { 210, "FURY CUTTER" },
        { 211, "STEEL WING" },
        { 212, "MEAN LOOK" },
        { 213, "ATTRACT" },
        { 214, "SLEEP TALK" },
        { 215, "HEAL BELL" },
        { 216, "RETURN" },
        { 217, "PRESENT" },
        { 218, "FRUSTRATION" },
        { 219, "SAFEGUARD" },
        { 220, "PAIN SPLIT" },
        { 221, "SACRED FIRE" },
        { 222, "MAGNITUDE" },
        { 223, "DYNAMICPUNCH" },
        { 224, "MEGAHORN" },
        { 225, "DRAGONBREATH" },
        { 226, "BATON PASS" },
        { 227, "ENCORE" },
        { 228, "PURSUIT" },
        { 229, "RAPID SPIN" },
        { 230, "SWEET SCENT" },
        { 231, "IRON TAIL" },
        { 232, "METAL CLAW" },
        { 233, "VITAL THROW" },
        { 234, "MORNING SUN" },
        { 235, "SYNTHESIS" },
        { 236, "MOONLIGHT" },
        { 237, "HIDDEN POWER" },
        { 238, "CROSS CHOP" },
        { 239, "TWISTER" },
        { 240, "RAIN DANCE" },
        { 241, "SUNNY DAY" },
        { 242, "CRUNCH" },
        { 243, "MIRROR COAT" },
        { 244, "PSYCH UP" },
        { 245, "EXTREMESPEED" },
        { 246, "ANCIENTPOWER" },
        { 247, "SHADOW BALL" },
        { 248, "FUTURE SIGHT" },
        { 249, "ROCK SMASH" },
        { 250, "WHIRLPOOL" },
        { 251, "BEAT UP" },
        { 252, "FAKE OUT" },
        { 253, "UPROAR" },
        { 254, "STOCKPILE" },
        { 255, "SPIT UP" },
        { 256, "SWALLOW" },
        { 257, "HEAT WAVE" },
        { 258, "HAIL" },
        { 259, "TORMENT" },
        { 260, "FLATTER" },
        { 261, "WILL-O-WISP" },
        { 262, "MEMENTO" },
        { 263, "FACADE" },
        { 264, "FOCUS PUNCH" },
        { 265, "SMELLINGSALT" },
        { 266, "FOLLOW ME" },
        { 267, "NATURE POWER" },
        { 268, "CHARGE" },
        { 269, "TAUNT" },
        { 270, "HELPING HAND" },
        { 271, "TRICK" },
        { 272, "ROLE PLAY" },
        { 273, "WISH" },
        { 274, "ASSIST" },
        { 275, "INGRAIN" },
        { 276, "SUPERPOWER" },
        { 277, "MAGIC COAT" },
        { 278, "RECYCLE" },
        { 279, "REVENGE" },
        { 280, "BRICK BREAK" },
        { 281, "YAWN" },
        { 282, "KNOCK OFF" },
        { 283, "ENDEAVOR" },
        { 284, "ERUPTION" },
        { 285, "SKILL SWAP" },
        { 286, "IMPRISON" },
        { 287, "REFRESH" },
        { 288, "GRUDGE" },
        { 289, "SNATCH" },
        { 290, "SECRET POWER" },
        { 291, "DIVE" },
        { 292, "ARM THRUST" },
        { 293, "CAMOUFLAGE" },
        { 294, "TAIL GLOW" },
        { 295, "LUSTER PURGE" },
        { 296, "MIST BALL" },
        { 297, "FEATHERDANCE" },
        { 298, "TEETER DANCE" },
        { 299, "BLAZE KICK" },
        { 300, "MUD SPORT" },
        { 301, "ICE BALL" },
        { 302, "NEEDLE ARM" },
        { 303, "SLACK OFF" },
        { 304, "HYPER VOICE" },
        { 305, "POISON FANG" },
        { 306, "CRUSH CLAW" },
        { 307, "BLAST BURN" },
        { 308, "HYDRO CANNON" },
        { 309, "METEOR MASH" },
        { 310, "ASTONISH" },
        { 311, "WEATHER BALL" },
        { 312, "AROMATHERAPY" },
        { 313, "FAKE TEARS" },
        { 314, "AIR CUTTER" },
        { 315, "OVERHEAT" },
        { 316, "ODOR SLEUTH" },
        { 317, "ROCK TOMB" },
        { 318, "SILVER WIND" },
        { 319, "METAL SOUND" },
        { 320, "GRASSWHISTLE" },
        { 321, "TICKLE" },
        { 322, "COSMIC POWER" },
        { 323, "WATER SPOUT" },
        { 324, "SIGNAL BEAM" },
        { 325, "SHADOW PUNCH" },
        { 326, "EXTRASENSORY" },
        { 327, "SKY UPPERCUT" },
        { 328, "SAND TOMB" },
        { 329, "SHEER COLD" },
        { 330, "MUDDY WATER" },
        { 331, "BULLET SEED" },
        { 332, "AERIAL ACE" },
        { 333, "ICICLE SPEAR" },
        { 334, "IRON DEFENSE" },
        { 335, "BLOCK" },
        { 336, "HOWL" },
        { 337, "DRAGON CLAW" },
        { 338, "FRENZY PLANT" },
        { 339, "BULK UP" },
        { 340, "BOUNCE" },
        { 341, "MUD SHOT" },
        { 342, "POISON TAIL" },
        { 343, "COVET" },
        { 344, "VOLT TACKLE" },
        { 345, "MAGICAL LEAF" },
        { 346, "WATER SPORT" },
        { 347, "CALM MIND" },
        { 348, "LEAF BLADE" },
        { 349, "DRAGON DANCE" },
        { 350, "ROCK BLAST" },
        { 351, "SHOCK WAVE" },
        { 352, "WATER PULSE" },
        { 353, "DOOM DESIRE" },
        { 354, "PSYCHO BOOST" },
      };
    }
    public Dictionary<Ribbon, string> Ribbons {
      get => new() {
        { Ribbon.Cool, "Cool" },
        { Ribbon.Beauty, "Beauty" },
        { Ribbon.Cute, "Cute" },
        { Ribbon.Smart, "Smart" },
        { Ribbon.Tough, "Tough" },
        { Ribbon.Champion, "Champion" },
        { Ribbon.Winning, "Winning" },
        { Ribbon.Victory, "Victory" },
        { Ribbon.Artist, "Artist" },
        { Ribbon.Effort, "Effort" },
        { Ribbon.BattleChampion, "BattleChampion" },
        { Ribbon.RegionalChampion, "RegionalChampion" },
        { Ribbon.NationalChampion, "NationalChampion" },
        { Ribbon.Country, "Country" },
        { Ribbon.National, "National" },
        { Ribbon.Earth, "Earth" },
        { Ribbon.World, "World" },
        { Ribbon.None, "-" },
      };
    }
    public Dictionary<PokemonType, string> PokemonTypes {
      get => new() {
        { PokemonType.Normal, "Normal" },
        { PokemonType.Fighting, "Fighting" },
        { PokemonType.Flying, "Flying" },
        { PokemonType.Poison, "Poison" },
        { PokemonType.Ground, "Ground" },
        { PokemonType.Rock, "Rock" },
        { PokemonType.Bug, "Bug" },
        { PokemonType.Ghost, "Ghost" },
        { PokemonType.Steel, "Steel" },
        { PokemonType.Unknown, "Unknown" },
        { PokemonType.Fire, "Fire" },
        { PokemonType.Water, "Water" },
        { PokemonType.Grass, "Grass" },
        { PokemonType.Electric, "Electric" },
        { PokemonType.Psychic, "Psychic" },
        { PokemonType.Ice, "Ice" },
        { PokemonType.Dragon, "Dragon" },
        { PokemonType.Dark, "Dark" },
      };
    }
    public Dictionary<HiddenPowerType, string> HiddenPowerTypes {
      get => new() {
        { HiddenPowerType.Fighting, "Fighting" },
        { HiddenPowerType.Flying, "Flying" },
        { HiddenPowerType.Poison, "Poison" },
        { HiddenPowerType.Ground, "Ground" },
        { HiddenPowerType.Rock, "Rock" },
        { HiddenPowerType.Bug, "Bug" },
        { HiddenPowerType.Ghost, "Ghost" },
        { HiddenPowerType.Steel, "Steel" },
        { HiddenPowerType.Fire, "Fire" },
        { HiddenPowerType.Water, "Water" },
        { HiddenPowerType.Grass, "Grass" },
        { HiddenPowerType.Electric, "Electric" },
        { HiddenPowerType.Psychic, "Psychic" },
        { HiddenPowerType.Ice, "Ice" },
        { HiddenPowerType.Dragon, "Dragon" },
        { HiddenPowerType.Dark, "Dark" },
      };
    }
  }
  public class ConstKO : IConst {
    public Dictionary<Gender, string> Gender {
      get => new() {
        { Pokemon.Gender.Male, "남성" },
        { Pokemon.Gender.Female, "여성" },
        { Pokemon.Gender.Unknown, "Unknown" }
      };
    }
    public Dictionary<Nature, string> Nature {
      get => new() {
        { Pokemon.Nature.Hardy, "노력" },
        { Pokemon.Nature.Lonely, "외로움" },
        { Pokemon.Nature.Brave, "용감" },
        { Pokemon.Nature.Adamant, "고집" },
        { Pokemon.Nature.Naughty, "개구쟁이" },
        { Pokemon.Nature.Bold, "대담" },
        { Pokemon.Nature.Docile, "온순" },
        { Pokemon.Nature.Relaxed, "무사태평" },
        { Pokemon.Nature.Impish, "장난꾸러기" },
        { Pokemon.Nature.Lax, "촐랑" },
        { Pokemon.Nature.Timid, "겁쟁이" },
        { Pokemon.Nature.Hasty, "성급" },
        { Pokemon.Nature.Serious, "성실" },
        { Pokemon.Nature.Jolly, "명랑" },
        { Pokemon.Nature.Naive, "천진난만" },
        { Pokemon.Nature.Modest, "조심" },
        { Pokemon.Nature.Mild, "의젓" },
        { Pokemon.Nature.Quiet, "냉정" },
        { Pokemon.Nature.Bashful, "수줍음" },
        { Pokemon.Nature.Rash, "덜렁" },
        { Pokemon.Nature.Calm, "차분" },
        { Pokemon.Nature.Gentle, "얌전" },
        { Pokemon.Nature.Sassy, "건방" },
        { Pokemon.Nature.Careful, "신중" },
        { Pokemon.Nature.Quirky, "변덕" },
      };
    }
    public Dictionary<StatusCondition, string> StatusCondition {
      get => new() {
        { Pokemon.StatusCondition.None, "-" },
        { Pokemon.StatusCondition.Sleep, "잠듦" },
        { Pokemon.StatusCondition.Poison, "독" },
        { Pokemon.StatusCondition.Burn, "화상" },
        { Pokemon.StatusCondition.Freeze, "얼음" },
        { Pokemon.StatusCondition.Paralysis, "마비" },
        { Pokemon.StatusCondition.BadPoison, "맹독" },
      };
    }
    public Dictionary<Pokeball, string> Pokeball {
      get => new() {
        { Pokemon.Pokeball.MasterBall, "마스터볼" },
        { Pokemon.Pokeball.UltraBall, "하이퍼볼" },
        { Pokemon.Pokeball.GreatBall, "수퍼볼" },
        { Pokemon.Pokeball.PokeBall, "몬스터볼" },
        { Pokemon.Pokeball.SafariBall, "사파리볼" },
        { Pokemon.Pokeball.NetBall, "넷트볼" },
        { Pokemon.Pokeball.DiveBall, "다이브볼" },
        { Pokemon.Pokeball.NestBall, "네스트볼" },
        { Pokemon.Pokeball.RepeatBall, "리피트볼" },
        { Pokemon.Pokeball.TimerBall, "타이마볼" },
        { Pokemon.Pokeball.LuxuryBall, "럭셔리볼" },
        { Pokemon.Pokeball.PremierBall, "프레미어볼" },
      };
    }
    public Dictionary<PokemonLanguage, string> Language {
      get => new() {
        { PokemonLanguage.Japanese, "Japanese" },
        { PokemonLanguage.English, "English" },
        { PokemonLanguage.French, "French" },
        { PokemonLanguage.Italian, "Italian" },
        { PokemonLanguage.German, "German" },
        { PokemonLanguage.unused, "unused" },
        { PokemonLanguage.Spanish, "Spanish" },
      };
    }
    public string[] StatNames { get => ["HP", "공격", "방어", "스피드", "특수 공격", "특수 방어"]; }
    public string[] Locations {
      get => [
        "미로마을",
        "고도마을",
        "무로마을",
        "용암마을",
        "단풍마을",
        "잔디마을",
        "황금마을",
        "등화도시",
        "잿빛도시",
        "보라시티",
        "금탄도시",
        "검방울시티",
        "해안시티",
        "이끼시티",
        "루네시티",
        "그랜드시티",
        "101번 도로",
        "102번 도로",
        "103번 도로",
        "104번 도로",
        "105번 수로",
        "106번 수로",
        "107번 수로",
        "108번 수로",
        "109번 수로",
        "110번 도로",
        "111번 도로",
        "112번 도로",
        "113번 도로",
        "114번 도로",
        "115번 도로",
        "116번 도로",
        "117번 도로",
        "118번 도로",
        "119번 도로",
        "120번 도로",
        "121번 도로",
        "122번 수로",
        "123번 도로",
        "124번 수로",
        "125번 수로",
        "126번 수로",
        "127번 수로",
        "128번 수로",
        "129번 수로",
        "130번 수로",
        "131번 수로",
        "132번 수로",
        "133번 수로",
        "134번 수로",
        "수중 (124번 수로)",
        "수중 (126번 수로)",
        "수중 (127번 수로)",
        "수중 (128번 수로)",
        "수중 (루네시티)",
        "바위 동굴",
        "굴뚝산",
        "사파리존",
        "배틀프런티어",
        "등화숲",
        "금잔터널",
        "버려진 배",
        "뉴보라",
        "유성의 폭포",
        "유성의 폭포 (unused)",
        "송화산",
        "아쿠아단 아지트",
        "여울의 동굴",
        "해저동굴",
        "수중 (해저동굴)",
        "챔피언로드",
        "환상섬",
        "각성의 사당",
        "남쪽의 외딴섬",
        "불꽃샛길",
        "불꽃샛길 (unused)",
        "울퉁불퉁 산길",
        "울퉁불퉁 산길 (unused)",
        "고시의 석실",
        "수중 (134번 수로)",
        "가뭄의 암굴",
        "작은 섬 옆굴",
        "사막유적",
        "고대의 무덤",
        "트럭 안",
        "하늘기둥",
        "비밀기지",
        "타이드립호",
        "태초마을",
        "상록시티",
        "회색시티",
        "블루시티",
        "보라타운",
        "갈색시티",
        "무지개시티",
        "연분홍시티",
        "홍련섬",
        "석영고원",
        "노랑시티",
        "4번 도로",
        "10번 도로",
        "1번 도로",
        "2번 도로",
        "3번 도로",
        "4번 도로",
        "5번 도로",
        "6번 도로",
        "7번 도로",
        "8번 도로",
        "9번 도로",
        "10번 도로",
        "11번 도로",
        "12번 도로",
        "13번 도로",
        "14번 도로",
        "15번 도로",
        "16번 도로",
        "17번 도로",
        "18번 도로",
        "19번 수로",
        "20번 수로",
        "21번 수로",
        "22번 도로",
        "23번 도로",
        "24번 도로",
        "25번 도로",
        "상록숲",
        "달맞이산",
        "상트앙느호",
        "지하통로 (5-6번 도로)",
        "지하통로 (7-8번 도로)",
        "디그다의 굴",
        "챔피언로드",
        "로켓단아지트",
        "실프주식회사",
        "포켓몬저택",
        "사파리존",
        "포켓몬리그",
        "돌산터널",
        "쌍둥이섬",
        "포켓몬타워",
        "블루시티동굴",
        "무인발전소",
        "제1섬",
        "제2섬",
        "제3섬",
        "제4섬",
        "제5섬",
        "제7섬",
        "제6섬",
        "저녁노을길",
        "보물해변",
        "가장자리곶",
        "유대다리",
        "제3섬 항구",
        "6번 일곱섬",
        "7번 일곱섬",
        "8번 일곱섬",
        "9번 일곱섬",
        "호화리조트",
        "물의 미로",
        "제5섬 공터",
        "추억탑",
        "변두리의 섬",
        "녹색산책길",
        "물의 산책길",
        "유적의 골짜기",
        "트레이너타워",
        "계곡입구",
        "칠보계곡",
        "옥포그리유적",
        "22번 일곱섬",
        "23번 일곱섬",
        "24번 일곱섬",
        "배꼽바위",
        "횃불산",
        "나무열매숲",
        "얼음폭포동굴",
        "로켓단창고",
        "트레이너타워",
        "점의 굴",
        "돌아올 수 없는 굴",
        "증표숲",
        "변형동굴",
        "옥포그리의 석실",
        "제3섬 통로",
        "옥포그리의 열쇠",
        "탄생의 섬",
        "이라님의 석실",
        "이그레안의 석실",
        "모스루프의 석실",
        "톡크로에의 석실",
        "루마네즈의 석실",
        "우무누스의 석실",
        "움노브리의 석실",
        "횃불온천",
        "레드 그린 특수",
        "아쿠아단 아지트",
        "마그마단 아지트",
        "환영탑",
        "탄생의 섬",
        "끝자락의 외딴섬",
        "아틀리에의 굴",
        "바다 동굴",
        "수로 (바다 동굴)",
        "육지 동굴",
        "수로 (105번 수로)",
        "수로 (125번 수로)",
        "수로 (129번 수로)",
        "사막의 지하도",
        "변형동굴",
        "배꼽바위",
        "트레이너힐",
        "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "",
        "", "", "", "", "", "", "", "", "", "",
        "(gift egg)",
        "(in-game trade)",
        "(운명적인 만남)"
      ];
    }
    public Dictionary<int, string> Moves {
      get => new() {
        { 001, "막치기" },
        { 002, "태권당수" },
        { 003, "연속뺨치기" },
        { 004, "연속펀치" },
        { 005, "메가톤펀치" },
        { 006, "고양이돈받기" },
        { 007, "불꽃펀치" },
        { 008, "냉동펀치" },
        { 009, "번개펀치" },
        { 010, "할퀴기" },
        { 011, "찝기" },
        { 012, "가위자르기" },
        { 013, "칼바람" },
        { 014, "칼춤" },
        { 015, "풀베기" },
        { 016, "바람일으키기" },
        { 017, "날개치기" },
        { 018, "날려버리기" },
        { 019, "공중날기" },
        { 020, "조이기" },
        { 021, "힘껏치기" },
        { 022, "덩굴채찍" },
        { 023, "짓밟기" },
        { 024, "두번치기" },
        { 025, "메가톤킥" },
        { 026, "점프킥" },
        { 027, "돌려차기" },
        { 028, "모래뿌리기" },
        { 029, "박치기" },
        { 030, "뿔찌르기" },
        { 031, "마구찌르기" },
        { 032, "뿔드릴" },
        { 033, "몸통박치기" },
        { 034, "누르기" },
        { 035, "김밥말이" },
        { 036, "돌진" },
        { 037, "난동부리기" },
        { 038, "이판사판태클" },
        { 039, "꼬리흔들기" },
        { 040, "독침" },
        { 041, "더블니들" },
        { 042, "바늘미사일" },
        { 043, "째려보기" },
        { 044, "물기" },
        { 045, "울음소리" },
        { 046, "울부짖기" },
        { 047, "노래하기" },
        { 048, "초음파" },
        { 049, "소닉붐" },
        { 050, "사슬묶기" },
        { 051, "용해액" },
        { 052, "불꽃세례" },
        { 053, "화염방사" },
        { 054, "흰안개" },
        { 055, "물대포" },
        { 056, "하이드로펌프" },
        { 057, "파도타기" },
        { 058, "냉동빔" },
        { 059, "눈보라" },
        { 060, "환상빔" },
        { 061, "거품광선" },
        { 062, "오로라빔" },
        { 063, "파괴광선" },
        { 064, "쪼기" },
        { 065, "회전부리" },
        { 066, "지옥의바퀴" },
        { 067, "안다리걸기" },
        { 068, "카운터" },
        { 069, "지구던지기" },
        { 070, "괴력" },
        { 071, "흡수" },
        { 072, "메가드레인" },
        { 073, "씨뿌리기" },
        { 074, "성장" },
        { 075, "잎날가르기" },
        { 076, "솔라빔" },
        { 077, "독가루" },
        { 078, "저리가루" },
        { 079, "수면가루" },
        { 080, "꽃잎댄스" },
        { 081, "실뿜기" },
        { 082, "용의분노" },
        { 083, "회오리불꽃" },
        { 084, "전기쇼크" },
        { 085, "10만볼트" },
        { 086, "전기자석파" },
        { 087, "번개" },
        { 088, "돌떨구기" },
        { 089, "지진" },
        { 090, "땅가르기" },
        { 091, "구멍파기" },
        { 092, "맹독" },
        { 093, "염동력" },
        { 094, "사이코키네시스" },
        { 095, "최면술" },
        { 096, "요가포즈" },
        { 097, "고속이동" },
        { 098, "전광석화" },
        { 099, "분노" },
        { 100, "순간이동" },
        { 101, "나이트헤드" },
        { 102, "흉내내기" },
        { 103, "싫은소리" },
        { 104, "그림자분신" },
        { 105, "HP회복" },
        { 106, "단단해지기" },
        { 107, "작아지기" },
        { 108, "연막" },
        { 109, "이상한빛" },
        { 110, "껍질에숨기" },
        { 111, "웅크리기" },
        { 112, "배리어" },
        { 113, "빛의장막" },
        { 114, "흑안개" },
        { 115, "리플렉터" },
        { 116, "기충전" },
        { 117, "참기" },
        { 118, "손가락흔들기" },
        { 119, "따라하기" },
        { 120, "자폭" },
        { 121, "알폭탄" },
        { 122, "핥기" },
        { 123, "스모그" },
        { 124, "오물공격" },
        { 125, "뼈다귀치기" },
        { 126, "불대문자" },
        { 127, "폭포오르기" },
        { 128, "껍질끼우기" },
        { 129, "스피드스타" },
        { 130, "로케트박치기" },
        { 131, "가시대포" },
        { 132, "휘감기" },
        { 133, "망각술" },
        { 134, "숟가락휘기" },
        { 135, "알낳기" },
        { 136, "무릎차기" },
        { 137, "뱀눈초리" },
        { 138, "꿈먹기" },
        { 139, "독가스" },
        { 140, "구슬던지기" },
        { 141, "흡혈" },
        { 142, "악마의키스" },
        { 143, "불새" },
        { 144, "변신" },
        { 145, "거품" },
        { 146, "잼잼펀치" },
        { 147, "버섯포자" },
        { 148, "플래시" },
        { 149, "사이코웨이브" },
        { 150, "튀어오르기" },
        { 151, "녹기" },
        { 152, "찝게햄머" },
        { 153, "대폭발" },
        { 154, "마구할퀴기" },
        { 155, "뼈다귀부메랑" },
        { 156, "잠자기" },
        { 157, "스톤샤워" },
        { 158, "필살앞니" },
        { 159, "각지기" },
        { 160, "텍스처" },
        { 161, "트라이어택" },
        { 162, "분노의앞니" },
        { 163, "베어가르기" },
        { 164, "대타출동" },
        { 165, "발버둥" },
        { 166, "스케치" },
        { 167, "트리플킥" },
        { 168, "도둑질" },
        { 169, "거미집" },
        { 170, "마음의눈" },
        { 171, "악몽" },
        { 172, "화염자동차" },
        { 173, "코골기" },
        { 174, "저주" },
        { 175, "바둥바둥" },
        { 176, "텍스처2" },
        { 177, "에어로블라스트" },
        { 178, "목화포자" },
        { 179, "기사회생" },
        { 180, "원한" },
        { 181, "눈싸라기" },
        { 182, "방어" },
        { 183, "마하펀치" },
        { 184, "겁나는얼굴" },
        { 185, "속여때리기" },
        { 186, "천사의키스" },
        { 187, "배북" },
        { 188, "오물폭탄" },
        { 189, "진흙뿌리기" },
        { 190, "대포무노포" },
        { 191, "압정뿌리기" },
        { 192, "전자포" },
        { 193, "꿰뚫어보기" },
        { 194, "길동무" },
        { 195, "멸망의노래" },
        { 196, "얼다바람" },
        { 197, "판별" },
        { 198, "본러쉬" },
        { 199, "록온" },
        { 200, "역린" },
        { 201, "모래바람" },
        { 202, "기가드레인" },
        { 203, "버티기" },
        { 204, "애교부리기" },
        { 205, "구르기" },
        { 206, "칼등치기" },
        { 207, "뽐내기" },
        { 208, "우유마시기" },
        { 209, "스파크" },
        { 210, "연속자르기" },
        { 211, "강철날개" },
        { 212, "검은눈빛" },
        { 213, "헤롱헤롱" },
        { 214, "잠꼬대" },
        { 215, "치료방울" },
        { 216, "은혜갚기" },
        { 217, "프레젠트" },
        { 218, "화풀이" },
        { 219, "신비의부적" },
        { 220, "아픔나누기" },
        { 221, "성스러운불꽃" },
        { 222, "매그니튜드" },
        { 223, "폭발펀치" },
        { 224, "메가폰" },
        { 225, "용의숨결" },
        { 226, "바톤터치" },
        { 227, "앵콜" },
        { 228, "따라가때리기" },
        { 229, "고속스핀" },
        { 230, "달콤한향기" },
        { 231, "아이언테일" },
        { 232, "메탈크로우" },
        { 233, "받아던지기" },
        { 234, "아침햇살" },
        { 235, "광합성" },
        { 236, "달의불빛" },
        { 237, "잠재파워" },
        { 238, "크로스촙" },
        { 239, "회오리" },
        { 240, "비바라기" },
        { 241, "쾌청" },
        { 242, "깨물어부수기" },
        { 243, "미러코트" },
        { 244, "자기암시" },
        { 245, "신속" },
        { 246, "원시의힘" },
        { 247, "섀도볼" },
        { 248, "미래예지" },
        { 249, "바위깨기" },
        { 250, "바다회오리" },
        { 251, "집단구타" },
        { 252, "속이다" },
        { 253, "소란피기" },
        { 254, "비축하기" },
        { 255, "토해내기" },
        { 256, "꿀꺽" },
        { 257, "열풍" },
        { 258, "싸라기눈" },
        { 259, "트집" },
        { 260, "부추기기" },
        { 261, "도깨비불" },
        { 262, "추억의선물" },
        { 263, "객기" },
        { 264, "힘껏펀치" },
        { 265, "정신차리기" },
        { 266, "날따름" },
        { 267, "자연의힘" },
        { 268, "충전" },
        { 269, "도발" },
        { 270, "도우미" },
        { 271, "트릭" },
        { 272, "역할" },
        { 273, "희망사항" },
        { 274, "조수" },
        { 275, "뿌리박기" },
        { 276, "엄청난힘" },
        { 277, "매직코트" },
        { 278, "리사이클" },
        { 279, "리벤지" },
        { 280, "깨트리다" },
        { 281, "하품" },
        { 282, "탁쳐서떨구기" },
        { 283, "죽기살기" },
        { 284, "분화" },
        { 285, "스킬스웹" },
        { 286, "봉인" },
        { 287, "리프레쉬" },
        { 288, "원념" },
        { 289, "가로챔" },
        { 290, "비밀의힘" },
        { 291, "다이빙" },
        { 292, "손바닥치기" },
        { 293, "보호색" },
        { 294, "반딧불" },
        { 295, "라스트버지" },
        { 296, "미스트볼" },
        { 297, "깃털댄스" },
        { 298, "흔들흔들댄스" },
        { 299, "브레이즈킥" },
        { 300, "흙놀이" },
        { 301, "아이스볼" },
        { 302, "바늘팔" },
        { 303, "태만함" },
        { 304, "하이퍼보이스" },
        { 305, "독엄니" },
        { 306, "브레이크크루" },
        { 307, "블러스트번" },
        { 308, "하이드로캐논" },
        { 309, "코멧펀치" },
        { 310, "놀래키기" },
        { 311, "웨더볼" },
        { 312, "아로마테라피" },
        { 313, "거짓울음" },
        { 314, "에어컷터" },
        { 315, "오버히트" },
        { 316, "냄새구별" },
        { 317, "암석봉인" },
        { 318, "은빛바람" },
        { 319, "금속음" },
        { 320, "풀피리" },
        { 321, "간지르기" },
        { 322, "코스믹파워" },
        { 323, "바지락조개" },
        { 324, "시그널빔" },
        { 325, "섀도펀치" },
        { 326, "신통력" },
        { 327, "스카이업퍼" },
        { 328, "모래지옥" },
        { 329, "절대영도" },
        { 330, "탁류" },
        { 331, "기관총" },
        { 332, "제비반환" },
        { 333, "고드름침" },
        { 334, "철벽" },
        { 335, "블록" },
        { 336, "멀리짖음" },
        { 337, "드래곤크루" },
        { 338, "하드플랜트" },
        { 339, "벌크업" },
        { 340, "뛰어오르다" },
        { 341, "머드숏" },
        { 342, "포이즌테일" },
        { 343, "탐내다" },
        { 344, "볼트태클" },
        { 345, "메지컬리프" },
        { 346, "물놀이" },
        { 347, "명상" },
        { 348, "리프블레이드" },
        { 349, "용의춤" },
        { 350, "락블레스트" },
        { 351, "전격파" },
        { 352, "물의파동" },
        { 353, "파멸의소원" },
        { 354, "사이코부스트" },
      };
    }
    public Dictionary<Ribbon, string> Ribbons {
      get => new() {
        { Ribbon.Cool, "쿨" },
        { Ribbon.Beauty, "뷰티" },
        { Ribbon.Cute, "큐트" },
        { Ribbon.Smart, "지니어스" },
        { Ribbon.Tough, "파워풀" },
        { Ribbon.Champion, "호연챔피언" },
        { Ribbon.Winning, "위닝" },
        { Ribbon.Victory, "빅토리" },
        { Ribbon.Artist, "브로마이드" },
        { Ribbon.Effort, "노력" },
        { Ribbon.BattleChampion, "마린" },
        { Ribbon.RegionalChampion, "랜드" },
        { Ribbon.NationalChampion, "스카이" },
        { Ribbon.Country, "컨트리" },
        { Ribbon.National, "내셔널" },
        { Ribbon.Earth, "어스" },
        { Ribbon.World, "월드" },
        { Ribbon.None, "-" },
      };
    }
    public Dictionary<PokemonType, string> PokemonTypes {
      get => new() {
        { PokemonType.Normal, "노말" },
        { PokemonType.Fighting, "격투" },
        { PokemonType.Flying, "비행" },
        { PokemonType.Poison, "독" },
        { PokemonType.Ground, "땅" },
        { PokemonType.Rock, "바위" },
        { PokemonType.Bug, "벌레" },
        { PokemonType.Ghost, "고스트" },
        { PokemonType.Steel, "강철" },
        { PokemonType.Unknown, "Unknown" },
        { PokemonType.Fire, "불꽃" },
        { PokemonType.Water, "물" },
        { PokemonType.Grass, "풀" },
        { PokemonType.Electric, "전기" },
        { PokemonType.Psychic, "에스퍼" },
        { PokemonType.Ice, "얼음" },
        { PokemonType.Dragon, "드래곤" },
        { PokemonType.Dark, "악" },
      };
    }
    public Dictionary<HiddenPowerType, string> HiddenPowerTypes {
      get => new() {
        { HiddenPowerType.Fighting, "격투" },
        { HiddenPowerType.Flying, "비행" },
        { HiddenPowerType.Poison, "독" },
        { HiddenPowerType.Ground, "땅" },
        { HiddenPowerType.Rock, "바위" },
        { HiddenPowerType.Bug, "벌레" },
        { HiddenPowerType.Ghost, "고스트" },
        { HiddenPowerType.Steel, "강철" },
        { HiddenPowerType.Fire, "불꽃" },
        { HiddenPowerType.Water, "물" },
        { HiddenPowerType.Grass, "풀" },
        { HiddenPowerType.Electric, "전기" },
        { HiddenPowerType.Psychic, "에스퍼" },
        { HiddenPowerType.Ice, "얼음" },
        { HiddenPowerType.Dragon, "드래곤" },
        { HiddenPowerType.Dark, "악" },
      };
    }
  }
  public static class Const {
    public static ConstEN EN = new();
    public static ConstKO KO = new();
    public static readonly string[] PokemonImage = [
      "",
      "c/c5/001MS3.png",
      "4/46/002MS3.png",
      "5/58/003MS3.png",
      "4/4b/004MS3.png",
      "9/90/005MS3.png",
      "6/67/006MS3.png",
      "1/1c/007MS3.png",
      "a/a8/008MS3.png",
      "3/3b/009MS3.png",
      "0/0b/010MS3.png",
      "c/ce/011MS3.png",
      "3/33/012MS3.png",
      "7/72/013MS3.png",
      "4/46/014MS3.png",
      "9/92/015MS3.png",
      "d/d8/016MS3.png",
      "c/ce/017MS3.png",
      "7/78/018MS3.png",
      "d/d8/019MS3.png",
      "b/be/020MS3.png",
      "e/e4/021MS3.png",
      "6/65/022MS3.png",
      "4/47/023MS3.png",
      "b/bd/024MS3.png",
      "2/20/025MS3.png",
      "d/d6/026MS3.png",
      "4/41/027MS3.png",
      "8/88/028MS3.png",
      "4/49/029MS3.png",
      "2/2f/030MS3.png",
      "6/64/031MS3.png",
      "b/b2/032MS3.png",
      "4/4a/033MS3.png",
      "f/f1/034MS3.png",
      "4/43/035MS3.png",
      "d/d7/036MS3.png",
      "4/46/037MS3.png",
      "c/ce/038MS3.png",
      "d/d3/039MS3.png",
      "e/e1/040MS3.png",
      "4/4a/041MS3.png",
      "9/9c/042MS3.png",
      "1/14/043MS3.png",
      "3/38/044MS3.png",
      "a/ad/045MS3.png",
      "7/7f/046MS3.png",
      "2/2a/047MS3.png",
      "3/31/048MS3.png",
      "a/a9/049MS3.png",
      "9/97/050MS3.png",
      "4/46/051MS3.png",
      "f/f6/052MS3.png",
      "5/5d/053MS3.png",
      "4/48/054MS3.png",
      "e/ed/055MS3.png",
      "8/8c/056MS3.png",
      "c/c3/057MS3.png",
      "0/0b/058MS3.png",
      "4/47/059MS3.png",
      "e/e0/060MS3.png",
      "7/79/061MS3.png",
      "4/43/062MS3.png",
      "f/fa/063MS3.png",
      "6/66/064MS3.png",
      "f/f8/065MS3.png",
      "1/14/066MS3.png",
      "b/b9/067MS3.png",
      "4/4d/068MS3.png",
      "1/1b/069MS3.png",
      "9/92/070MS3.png",
      "4/4b/071MS3.png",
      "5/59/072MS3.png",
      "6/67/073MS3.png",
      "7/7d/074MS3.png",
      "2/21/075MS3.png",
      "3/3c/076MS3.png",
      "7/7b/077MS3.png",
      "7/7b/077MS3.png",
      "c/cc/079MS3.png",
      "f/f1/080MS3.png",
      "a/a2/081MS3.png",
      "7/74/082MS3.png",
      "7/73/083MS3.png",
      "c/ca/084MS3.png",
      "9/9a/085MS3.png",
      "9/90/086MS3.png",
      "5/5c/087MS3.png",
      "4/40/088MS3.png",
      "c/c1/089MS3.png",
      "e/e4/090MS3.png",
      "4/4c/091MS3.png",
      "f/f8/092MS3.png",
      "5/5c/093MS3.png",
      "2/26/094MS3.png",
      "e/e4/095MS3.png",
      "4/4d/096MS3.png",
      "6/6c/097MS3.png",
      "d/d2/098MS3.png",
      "6/66/099MS3.png",
      "7/7e/100MS3.png",
      "6/61/101MS3.png",
      "b/bd/102MS3.png",
      "6/69/103MS3.png",
      "2/2e/104MS3.png",
      "4/4a/105MS3.png",
      "8/8b/106MS3.png",
      "2/2b/107MS3.png",
      "5/5e/108MS3.png",
      "a/a9/109MS3.png",
      "2/28/110MS3.png",
      "c/c5/111MS3.png",
      "4/44/112MS3.png",
      "1/16/113MS3.png",
      "9/96/114MS3.png",
      "7/71/115MS3.png",
      "2/2e/116MS3.png",
      "c/c6/117MS3.png",
      "3/3b/118MS3.png",
      "5/5d/119MS3.png",
      "8/83/120MS3.png",
      "5/55/121MS3.png",
      "c/c0/122MS3.png",
      "6/6d/123MS3.png",
      "1/15/124MS3.png",
      "2/21/125MS3.png",
      "a/a4/126MS3.png",
      "a/aa/127MS3.png",
      "d/dd/128MS3.png",
      "3/33/129MS3.png",
      "f/fc/130MS3.png",
      "b/be/131MS3.png",
      "a/a6/132MS3.png",
      "f/f7/133MS3.png",
      "6/62/134MS3.png",
      "1/14/135MS3.png",
      "4/48/136MS3.png",
      "d/d9/137MS3.png",
      "6/61/138MS3.png",
      "3/35/139MS3.png",
      "9/99/140MS3.png",
      "8/8f/141MS3.png",
      "9/9d/142MS3.png",
      "9/90/143MS3.png",
      "8/8f/144MS3.png",
      "1/16/145MS3.png",
      "c/c0/146MS3.png",
      "5/51/147MS3.png",
      "3/37/148MS3.png",
      "f/ff/149MS3.png",
      "4/4f/150MS3.png",
      "e/e6/151MS3.png",
      "9/90/152MS3.png",
      "4/42/153MS3.png",
      "0/01/154MS3.png",
      "8/8e/155MS3.png",
      "6/66/156MS3.png",
      "8/8c/157MS3.png",
      "4/48/158MS3.png",
      "f/ff/159MS3.png",
      "5/5e/160MS3.png",
      "5/59/161MS3.png",
      "4/41/162MS3.png",
      "6/67/163MS3.png",
      "d/d2/164MS3.png",
      "9/99/165MS3.png",
      "a/a2/166MS3.png",
      "3/3f/167MS3.png",
      "5/53/168MS3.png",
      "6/61/169MS3.png",
      "c/c0/170MS3.png",
      "c/c6/171MS3.png",
      "9/9a/172MS3.png",
      "3/36/173MS3.png",
      "d/d6/174MS3.png",
      "a/a3/175MS3.png",
      "5/57/176MS3.png",
      "1/1f/177MS3.png",
      "d/df/178MS3.png",
      "1/1b/179MS3.png",
      "1/1b/180MS3.png",
      "b/b9/181MS3.png",
      "d/d5/182MS3.png",
      "0/02/183MS3.png",
      "7/76/184MS3.png",
      "8/82/185MS3.png",
      "5/58/186MS3.png",
      "c/cf/187MS3.png",
      "1/1f/188MS3.png",
      "a/a1/189MS3.png",
      "0/06/190MS3.png",
      "5/5d/191MS3.png",
      "7/74/192MS3.png",
      "9/96/193MS3.png",
      "7/7d/194MS3.png",
      "a/a0/195MS3.png",
      "f/f4/196MS3.png",
      "e/e3/197MS3.png",
      "0/0f/198MS3.png",
      "6/6d/199MS3.png",
      "4/4d/200MS3.png",
      "9/9f/201MS3.png",
      "9/95/202MS3.png",
      "5/5c/203MS3.png",
      "0/0e/204MS3.png",
      "a/a1/205MS3.png",
      "b/bc/206MS3.png",
      "f/fd/207MS3.png",
      "2/22/208MS3.png",
      "1/15/209MS3.png",
      "8/8a/210MS3.png",
      "f/f1/211MS3.png",
      "8/81/212MS3.png",
      "3/37/213MS3.png",
      "9/9e/214MS3.png",
      "3/30/215MS3.png",
      "5/53/216MS3.png",
      "1/12/217MS3.png",
      "5/5d/218MS3.png",
      "4/4d/219MS3.png",
      "0/0f/220MS3.png",
      "4/45/221MS3.png",
      "f/f7/222MS3.png",
      "a/a0/223MS3.png",
      "9/93/224MS3.png",
      "3/30/225MS3.png",
      "c/cc/226MS3.png",
      "c/cf/227MS3.png",
      "3/35/228MS3.png",
      "4/4f/229MS3.png",
      "7/74/230MS3.png",
      "e/ed/231MS3.png",
      "3/3e/232MS3.png",
      "6/6e/233MS3.png",
      "5/59/234MS3.png",
      "7/7c/235MS3.png",
      "1/16/236MS3.png",
      "8/8d/237MS3.png",
      "1/14/238MS3.png",
      "8/82/239MS3.png",
      "6/60/240MS3.png",
      "b/b0/241MS3.png",
      "c/cb/242MS3.png",
      "5/53/243MS3.png",
      "8/8a/244MS3.png",
      "a/a9/245MS3.png",
      "6/6e/246MS3.png",
      "2/29/247MS3.png",
      "7/76/248MS3.png",
      "e/e8/249MS3.png",
      "4/40/250MS3.png",
      "d/dc/251MS3.png",
      "", "", "", "", "", "", "", "", "", "",
      "", "", "", "", "", "", "", "", "", "",
      "", "", "", "", "",
      "d/d6/252MS3.png",
      "1/14/253MS3.png",
      "5/56/254MS3.png",
      "f/fb/255MS3.png",
      "d/d9/256MS3.png",
      "8/83/257MS3.png",
      "6/62/258MS3.png",
      "b/b2/259MS3.png",
      "a/a5/260MS3.png",
      "9/93/261MS3.png",
      "3/37/262MS3.png",
      "8/89/263MS3.png",
      "0/03/264MS3.png",
      "e/ec/265MS3.png",
      "a/a7/266MS3.png",
      "1/1e/267MS3.png",
      "4/45/268MS3.png",
      "9/9f/269MS3.png",
      "4/4e/270MS3.png",
      "d/dc/271MS3.png",
      "f/f9/272MS3.png",
      "5/57/273MS3.png",
      "a/ae/274MS3.png",
      "9/90/275MS3.png",
      "b/b3/290MS3.png",
      "7/76/291MS3.png",
      "5/5f/292MS3.png",
      "a/a7/276MS3.png",
      "a/a4/277MS3.png",
      "e/e8/285MS3.png",
      "8/81/286MS3.png",
      "2/26/327MS3.png",
      "5/55/278MS3.png",
      "8/88/279MS3.png",
      "1/1a/283MS3.png",
      "8/89/284MS3.png",
      "8/86/320MS3.png",
      "8/88/321MS3.png",
      "0/00/300MS3.png",
      "7/75/301MS3.png",
      "e/ee/352MS3.png",
      "3/32/343MS3.png",
      "7/7d/344MS3.png",
      "d/d1/299MS3.png",
      "0/0c/324MS3.png",
      "b/bf/302MS3.png",
      "2/27/339MS3.png",
      "b/bd/340MS3.png",
      "6/68/370MS3.png",
      "5/51/341MS3.png",
      "4/47/342MS3.png",
      "c/cc/349MS3.png",
      "1/18/350MS3.png",
      "d/da/318MS3.png",
      "5/58/319MS3.png",
      "9/9f/330MS3.png",
      "b/bf/331MS3.png",
      "1/1f/332MS3.png",
      "8/81/296MS3.png",
      "d/d5/297MS3.png",
      "4/4a/309MS3.png",
      "a/aa/310MS3.png",
      "8/8e/322MS3.png",
      "4/4c/323MS3.png",
      "e/ef/363MS3.png",
      "0/08/364MS3.png",
      "6/6b/365MS3.png",
      "5/5b/331MS3.png",
      "c/c9/332MS3.png",
      "f/f5/361MS3.png",
      "0/06/362MS3.png",
      "3/3e/337MS3.png",
      "b/b6/338MS3.png",
      "9/92/298MS3.png",
      "e/e0/325MS3.png",
      "c/cb/326MS3.png",
      "d/d4/311MS3.png",
      "d/dc/312MS3.png",
      "8/8a/303MS3.png",
      "5/54/307MS3.png",
      "d/d5/308MS3.png",
      "0/05/333MS3.png",
      "9/94/334MS3.png",
      "8/8d/360MS3.png",
      "3/36/355MS3.png",
      "4/49/356MS3.png",
      "b/bf/315MS3.png",
      "b/b5/287MS3.png",
      "9/9c/288MS3.png",
      "4/46/289MS3.png",
      "f/fc/316MS3.png",
      "5/53/317MS3.png",
      "6/6b/357MS3.png",
      "c/c9/293MS3.png",
      "0/06/294MS3.png",
      "f/f6/295MS3.png",
      "8/81/366MS3.png",
      "e/e7/367MS3.png",
      "e/e1/368MS3.png",
      "5/50/359MS3.png",
      "7/72/353MS3.png",
      "2/23/354MS3.png",
      "c/c2/336MS3.png",
      "6/6c/335MS3.png",
      "4/46/369MS3.png",
      "c/c6/304MS3.png",
      "f/f1/305MS3.png",
      "3/34/306MS3.png",
      "e/e4/351MS3.png",
      "d/d6/313MS3.png",
      "b/bf/314MS3.png",
      "9/91/345MS3.png",
      "7/75/346MS3.png",
      "f/fc/347MS3.png",
      "3/32/348MS3.png",
      "8/81/280MS3.png",
      "1/1e/281MS3.png",
      "b/bf/282MS3.png",
      "3/3e/371MS3.png",
      "e/e8/372MS3.png",
      "e/e5/373MS3.png",
      "f/f1/374MS3.png",
      "b/b4/375MS3.png",
      "f/fb/376MS3.png",
      "8/8e/377MS3.png",
      "d/de/378MS3.png",
      "8/86/379MS3.png",
      "0/03/382MS3.png",
      "0/05/383MS3.png",
      "f/f2/384MS3.png",
      "4/41/380MS3.png",
      "5/56/381MS3.png",
      "9/94/385MS3.png",
      "b/bc/386MS3.png",
      "e/e1/358MS3.png",
      "6/68/EggMS3.png",
      "6/64/201BMS3.png",
      "3/31/201CMS3.png",
      "2/2c/201DMS3.png",
      "8/8b/201EMS3.png",
      "8/84/201FMS3.png",
      "6/65/201GMS3.png",
      "d/d3/201HMS3.png",
      "2/24/201IMS3.png",
      "a/a6/201JMS3.png",
      "9/9e/201KMS3.png",
      "6/6c/201LMS3.png",
      "8/83/201MMS3.png",
      "9/96/201NMS3.png",
      "b/b9/201OMS3.png",
      "2/23/201PMS3.png",
      "1/14/201QMS3.png",
      "2/24/201RMS3.png",
      "2/2e/201SMS3.png",
      "0/01/201TMS3.png",
      "c/cd/201UMS3.png",
      "1/10/201VMS3.png",
      "c/cc/201WMS3.png",
      "8/89/201XMS3.png",
      "5/53/201YMS3.png",
      "f/fb/201ZMS3.png",
      "3/32/201EXMS3.png",
      "9/94/201QUMS3.png",
      "d/dc/Spr_3r_Egg.png",
    ];
  }
}
